coverwallet/cw-components

examples/basic/app.css, examples/basic/app.js, lib/stylesheets/components/_oc_icon_option.scss, lib/stylesheets/components/_oc_list_option.scss, lib/stylesheets/components/_oc_select.scss, lib/stylesheets/components/_oc_selected_value.scss
=> [#112992027] Make only click select placeholder more visible 

lib/stylesheets/components/_icons_radio_group.scss, lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/n/projects/1594861/stories/142018565
Make flexboxes work properly on Ipads.
Use bourbon's mixin.
**Caveats**
None
Components will be rendered properly on old versions of Ipads.
=> Fix / Ipad's ui issues

package.json
* **Pivotal Story:** None
Update the styleguide to the last version.
By updating package version.
**Caveats**
None
The package will use the last version of the styleguide.
=> Chore / Update the styleguide

lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss
Reverts coverwallet/cw-components#72
=> Revert "[#142142737] Remove old style css class"

lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/142142737
* **Rollbar items:** no
The dark line
=> [#142142737] Remove old style css class

package.json
Upgrading to new version `2.6.0`.
=> Upgrading package version

examples/basic/app.js, lib/components/CwFlashNotification.jsx, lib/stylesheets/components/_cw_flash_notification.scss, lib/stylesheets/components/_oc_icon_option.scss, lib/stylesheets/components/_oc_select.scss, package.json
http://coverwallet.github.io/cw-components/basic/
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/144496383
* **Rollbar Errors:** No.
* **Related PRs:** No.
I new notification that will be used to give a long information. Also removed break words in the select buttons.
=> Adding a new notification and removing break-word in select buttons

examples/basic/app.js, lib/components/loader.jsx, lib/stylesheets/_variables.scss, lib/stylesheets/components/_loader.scss, lib/stylesheets/components/_oc_select.scss, lib/stylesheets/main.scss
**Pivotal Story:** https://www.pivotaltracker.com/story/show/149396265
We need a spinner with a message on any requoting page
Adding a new design for it.
**Mobile**
**Desktop**
=> Loading message

package.json
Updating package json version to update release in cw projects.
=> Updating package json

package.json
Adding the correct version for the package json.
=> Updating package json II

lib/stylesheets/components/_cw_flash_notification.scss, package.json
=> Updating notification styles

package.json
=> Package .json update

lib/components/BoxRadioGroup.jsx, lib/components/BoxRadioInput.jsx, lib/components/HighLightedText.jsx, lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, lib/components/InputKeyboard.jsx, lib/components/NumberInput.jsx, lib/components/OnlyClickIconOption.jsx, lib/components/OnlyClickIconOptions.jsx, lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, lib/components/OnlyClickSelect.jsx, lib/components/keyboard.jsx, lib/components/loader.jsx, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/151594342
As a Dev I should not see any deprecation warning
Fix PropTypes deprecation warnings
=> Fix PropTypes deprecation warning

lib/components/InputKeyboard.jsx, package.json
The ability to define the max length for the input keyboard
Usual
=> Add max length property to input keyboard

examples/basic/app.js, lib/components/Checkbox.jsx, lib/components/RadioInput.jsx, lib/components/RadioInputGroup.jsx, lib/index.js, package.json
**Pivotal Story** https://www.pivotaltracker.com/n/projects/2001641/stories/152003285
Add components for base checkbox and base radio group.
Retrieve the Checkbox component from the Binder app, and build the RadioGroup component in similar way how it's done for other radio groups (Icon- and Box- RadioGroup)
Check http://coverwallet.github.io/cw-components/basic/ after the changes are pushed to gh-pages.
As usual.
None.
=> Feature / checkbox radio inputs

lib/components/Checkbox.jsx, lib/stylesheets/components/_checkbox.scss, lib/stylesheets/components/_components.scss, package.json
Add ability to disable checkbox
=> Add ability to disable checkbox

package.json
Creating new version for the library
=> Fixing version

README.md
=> Update README with explanation about update package

examples/basic/app.js, lib/components/CurrencyInput.jsx, lib/components/__tests__/CurrencyInput.test.jsx, lib/index.js, lib/stylesheets/components/_components.scss, lib/stylesheets/components/_currency_input.scss, package.json, yarn.lock
Input that allows introducing currency values with cents.
Creating a new React input component for currency values with cents.
- Characters for decimal separator and thousands separator can be set.
- Min and max values can be set.
- Currency type can be set.
=> Creating currencyInput component

lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, package.json
Adding the possibility to disable one of the options in a radio group.
Adding or condition to the previous one:
`disabled={disabled || option.disabled}`
=> Adding the ability of disabling individual radio input in addition to radio group

lib/components/OnlyClickHideableSelect.js, lib/index.js, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/C4A-644
This multiselect needs for Direct appointments and Wholesalers/MGAs fields.
=> add miltiselect dropdown

lib/components/OnlyClickHideableSelect.js, package.json
* **Jira Story:** https://coverwallet.atlassian.net/browse/C4A-644
Needs to hide options list when the user selected one form them.
=> hide options when user choosed option

lib/components/OnlyClickHideableSelect.js, package.json, yarn.lock
* **Jira Story:** https://coverwallet.atlassian.net/browse/C4A-644
Close options on outside click
=> close options on outside click

README.md, lib/components/ButtonsListSelect.jsx, lib/components/ButtonsListSelectOption.jsx, lib/stylesheets/_colors.scss, lib/stylesheets/components/_question_icon.scss, lib/stylesheets/components/_wide_button.scss, package.json, yarn.lock
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-452_
Fix some bugs in the initial implementation (that's why a patch version will be published) and match the new design (only mobile) https://projects.invisionapp.com/d/main#/console/16121788/334301124/preview
=> Style tweaks

lib/stylesheets/components/_wide_button.scss, package.json
* **Jira Story:** https://coverwallet.atlassian.net/browse/ACQ-452
Fixed border and padding of wide button select elements
**BEFORE:**
**AFTER:**
=> Fixed wide button select element styles

lib/components/OnlyClickIconOptions.jsx, lib/components/OnlyClickSelect.jsx, package.json
* **Jira Story:** https://coverwallet.atlassian.net/browse/ACQ-542
Exposed the mouse enter/out events API to the external API
=> Open mouse events API

lib/components/QuestionIcon.jsx, lib/components/TextWithIcon.jsx, lib/components/__tests__/ButtonsListSelect.test.jsx, lib/stylesheets/_colors.scss, lib/stylesheets/components/_question_icon.scss, lib/stylesheets/components/_wide_button.scss, package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-373
Some changes were requested by UX review.
Tweaks based in this design:
https://invis.io/USPDVJZBPAH#/334301125_Mobile_Tooltip
Before:
After
=> Changes because of design requirements

lib/components/ButtonsListSelect.jsx, package.json
Added on view more click callback
=> added on view more click callback

lib/components/ButtonsListSelect.jsx, package.json
=> Hotfix: View more copy

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/stylesheets/components/_oc_select.scss, package.json
Feature: Added scrollable attribute to OnlyClickSelect.
=> Feature: Added scrollable attribute to OnlyClickSelect

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/components/__tests__/OnlyClickSelect.test.jsx, lib/stylesheets/components/_oc_select.scss, package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-737
Created new functionality: dropdown, that converts Onlyclickselect to an input disabled, with a dropdown.
New option: dropdown
=> Feature: onlyClickSelect Dropdownable

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/stylesheets/components/_oc_select.scss, package.json
Patch: 
- The input will not be rendered when has values, only when dropdown is true.
- Added new prop to close the list of the dropdown.
=> Patch: not render Input when has values, only when dropdown.

lib/components/OnlyClickSelect.jsx, package.json
Make api more explicit about its use with dropdown.
=> Fix: Clarify use of Dropdown

lib/stylesheets/components/_oc_select.scss, package.json
Revert changes from v2.18.0 in oc_select.scss
=> Hotfix: Revert changes from v2.18.0

lib/stylesheets/components/_oc_select.scss, package.json
Fix after the hotfix, related with scrollable functionality and dropdown icon.
=> Fix: scrollable and dropdown icon

lib/components/OnlyClickSelect.jsx, lib/stylesheets/components/_oc_select.scss, package.json
Fixed the layout of the property small-input for 38px of height.
=> Fix: OnlyclickSelect small-input layout

lib/components/OnlyClickSelect.jsx
* **Pivotal Story:** _Link to the PivotalTracker story_
* **Rollbar Errors:** _If there are related Rollbar errors link them here_
* **Related PRs:** _Provide links to related PRs if needed_
We must fix bug in prod that take place in agency onboarding flow. To reproduce go to agency onboarding flow -> go to the agent states page -> try to unselect state
=> Added the undefined check for event

examples/basic/app.js, lib/components/CurrencyInput.jsx, package.json
Added disabled attribute to currency input.
=> Feature: Added disabled attribute to currency input

examples/basic/app.js, lib/components/Toggle.jsx, lib/index.js, lib/stylesheets/components/_components.scss, lib/stylesheets/components/_toggle.scss, package.json
_Toggle component. Need it in `cw-node-docuemnts`. Try to reuse existing component from `payments-frontend`._
=> Add toggle component

examples/basic/app.js, lib/components/Tooltip.jsx, lib/components/TooltipIcon.jsx, lib/index.js, lib/stylesheets/components/_components.scss, lib/stylesheets/components/_tooltip.scss, package.json
_Add simple Tooltip and TooltipIcon components_
_Components receive tooltip text from props. So it can be used with or without redux_
=> Add Tooltip & TooltipIcon components

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/stylesheets/components/_oc_select.scss, package.json
We need to have component that have OnlyClickSelect behavior and view but doesn't have input.
=> Add hideInput prop

examples/basic/app.js, lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, lib/stylesheets/components/_icons_radio_group.scss, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/AONC-565
Due this history, it's necessary to add the possibility to set "recommendable" some icon radio inputs.
By enabling the possibility to pass an key "recommendable" to each option that receivces the component.
=> Add recommendable option to icon radio input

lib/stylesheets/components/_number_input.scss, package-lock.json, package.json
https://coverwallet.atlassian.net/browse/ACQ-1011
Remove spinner in input [type=number] for Chrome and Firefox. 
Add CSS style for input appearence.
=> Remove spinner in number-input for Chrome and Firefox

examples/basic/app.js, lib/components/NumPadMobile.jsx, lib/index.js, package.json
* **Jira Story:** 
https://coverwallet.atlassian.net/browse/LAN-74
https://coverwallet.atlassian.net/browse/DBS-1896
Created new component for mobile numpad keyboard and updated version
=> Created new component for mobile numpad keyboard and updated version

lib/components/NumPadMobile.jsx, package.json
* **JIRA Story:** 
https://coverwallet.atlassian.net/browse/LAN-74
https://coverwallet.atlassian.net/browse/DBS-1896
Missing setState for new component NumPadMobile.
=> Added SetState for new component

lib/components/NumPadMobile.jsx, package.json
* **Jira Story:** 
https://coverwallet.atlassian.net/browse/LAN-74
https://coverwallet.atlassian.net/browse/DBS-1896
Added missing use of the props setValue function.
=> Use the setvalue from props that was missing

lib/components/NumPadMobile.jsx, package.json
Refactor the code, removing redundant code.
=> Refactor new compoment

lib/components/InputKeyboard.jsx, package.json
This is not one specifically but: https://coverwallet.atlassian.net/browse/IN-1605
There is not onBlur functionality in the keyboard component and the dynamic tooltips require them
=> Add onBlur functionality to keyboard

lib/components/InputKeyboard.jsx, package.json
=> adding name to inputKeyboard

examples/basic/app.js, lib/components/ButtonsListSelect.jsx, lib/components/ButtonsListSelectOption.jsx, lib/components/ButtonsListSelectOptions.jsx, lib/components/CheckboxIcon.jsx, lib/stylesheets/components/_checkbox_icon.scss, lib/stylesheets/components/_components.scss, package.json
[Include checkbox to buttonsList](https://coverwallet.atlassian.net/browse/AONC-1331)
Add an option to include checkboxes in buttonsList component
- Creating checkbox icon component
- Adding a prop to select this behaviour, defaulted to false
=> Buttons list with checkboxes

lib/components/ButtonsListSelectOption.jsx, lib/components/CheckboxIcon.jsx, package.json
Fixing onClick for checkbox in SelectButtonList component
Adding onClick prop to CheckboxIcon component.
=> Fixing checkbox onClick

lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, package-lock.json
Add the option for providing an SVG icon as a prop so we don't have to reference the icons from our libraries as the only way of showing icons in cwRadioInputs
Adding a new property to the component and rendering it when passed as a prop
=> add new local icon option

package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/AONC-1449
* **Related PRs:** https://github.com/coverwallet/cw-components/pull/218
Wrong version.
=> 2.33.0 Fix repository version

lib/components/ButtonsListSelectOption.jsx, lib/stylesheets/components/_wide_button.scss, package-lock.json, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/AONC-1780
The behavior of the Upfront selection buttons is still inconsistent if the customer clicks slightly right from the center of the circle.
=> AONC-1780 Fix upfront selection buttons inconsistent behavior

examples/basic/app.js, lib/components/CurrencyInput.jsx, package-lock.json, package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/TRACK3-1979
we need to support ability to enter negative values in CurrencyInput component.
Notes: this ability was added before, but after several changes stopped working.
=> Fix negative values currency input

package-lock.json, package.json
Update dependencies to use only safe ones. 
All left vulnerabilities are related to devDeps only.
=> Update unsafe dependencies

lib/components/NumberInput.jsx, package-lock.json, package.json
=> add ability to specify placeholder for NumberInput

lib/components/OnlyClickHideableSelect.js, lib/components/OnlyClickSelect.jsx, lib/components/SelectWithManualInput.jsx, package-lock.json, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/IN-3353
Do not import full lodash library
Import only individual utilities
=> Do not import full lodash library

.circleci/config.yml, lib/components/AccordionSelect.jsx, lib/components/ButtonsListSelectOption.jsx, lib/components/ButtonsListSelectOptions.jsx, lib/stylesheets/components/_wide_button.scss, package-lock.json, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/ACQ-1412
* **Related PRs:** https://github.com/coverwallet/quotes-frontend/pull/2730
Add **disabled** prop and styles to ButtonsListSelectOption
=> ACQ-1412 add disabled prop to ButtonsListSelectOption

lib/components/InputKeyboard.jsx
Execute onChange coming from props when the value is going to be updated either by the action of the keyboard, or by the manual input.
=> InputKeyboard-execute_onChange_coming_from_props 

CHANGELOG.md, examples/basic/app.js, lib/components/OnlyClickSelect.jsx, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/IP-411
Include new prop to show selected value labels instead of values
=> IP-411 Include new prop for OnlyClickSelect

CHANGELOG.md, package-lock.json, package.json
=> Update package lock

.circleci/config.yml, CHANGELOG.md, README.md, examples/basic/app.js, lib/components/AccordionSelect.jsx, lib/components/ButtonsListSelect.jsx, lib/components/ButtonsListSelectOption.jsx, lib/components/ButtonsListSelectOptions.jsx, lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, lib/components/OnlyClickIconOption.jsx, lib/components/OnlyClickIconOptions.jsx, lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, lib/components/OnlyClickMultiSelect.jsx, lib/components/OnlyClickSelect.jsx, lib/components/Toggle.jsx, lib/components/WideButton.jsx, lib/utils/dataTestHelper.js, package-lock.json, package.json, yarn.lock
Release link: https://github.com/coverwallet/cw-components/releases/edit/untagged-055920ac093077b6fa82
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/AONC-4173
In order to have robust e2e tests we need to work with proper attributes, meaning we cannot rely on the usual ones such as class names since they can be updated for various reasons.
=> AON-3725 - add data test attributes for Cypress
