lib/stylesheets/components/_oc_icon_option.scss
Fix the problem with icon option labels:
=> Add word breaking to icon option label

examples/basic/app.js, lib/components/NumberInput.js, lib/stylesheets/components/_number_input.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/140669537
Adding the `CurrencyInput` component that will be used for inputting currency amounts.
- Extending the `NumberInput` component for supporting an extra parameter (`currency`)
- Adding the new component mode to the examples page
=> Extend NumberInput for currency edition

lib/stylesheets/components/_icons_radio_group.scss, lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss, lib/stylesheets/components/_oc_selected_value.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/n/projects/1594861/stories/142018569
Fix displaying of cw-components on old versions of ios.
Use bourbon's mixins for flexbox's options.
**Caveats**
None.
The components will properly be displayed on old versions of ios.
=> Fix / ui issues

lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss
Where
http://coverwallet.github.io/cw-components/basic/
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/142142737
* **Rollbar items:** no
The dark line
=> [#142142737] Remove old style css class

examples/basic/app.js, lib/components/CwFlashNotification.jsx, lib/stylesheets/components/_cw_flash_notification.scss, package.json
* **Pivotal Story:** None.
Extend flash messages with default close behaviour and fix children displaying.
If no `onClose` prop was passed use default close behaviour.
**Before**
**After**
Check flash messages section after deploying to gh-pages.
As usual.
None.
=> Extend flash messages

lib/stylesheets/components/_keyboard.scss
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/150355594
* **Rollbar Errors:** No.
* **Related PRs:** No.
Lines on the number button selection disappears when you click on them using IE11.
Adding some styles fixes.
**Before**
**After**
=> Fixing lines disapears when click on ei11

lib/stylesheets/components/_common.scss, lib/stylesheets/components/_components.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/151246943
* **Rollbar Errors:** No.
* **Related PRs:** No.
if you go to any bar to complete and you will see the X before saving it.
Applying the ::-ms-clear CSS pseudo-element which represents a button (the "clear button") at the edge of a text <input> which clears away the current value of the <input> element. 
**Before**
**After**
=> [#151246943] X in fields is not according to design on IE11

package.json
* **Pivotal Story:** https://www.pivotaltracker.com/story/show/151594342
As a Dev I should not see any deprecation warning
Bump react-highlight-words version
=> Bump react-highlight-words version to fix React deprecation warnings

examples/basic/app.js, lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, lib/components/OnlyClickMultiSelect.jsx, lib/index.js, lib/stylesheets/components/_components.scss, lib/stylesheets/components/_oc_list_option.scss, lib/stylesheets/components/_oc_multi_select.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/n/projects/2105824/stories/152349082
* **Rollbar Errors:** No.
* **Related PRs:** No.
Add a new field that permits multi-selection of different options. Create a variation of an existing one called Normal List view in our cw-components library http://coverwallet.github.io/cw-components/basic/
Added a new component OnlyClickMultiSelect. Reused components OnlyClickListOptions and OnlyClickListOption and added there a flag listType. For "multiSelect" listType set a new design according the requirements: 
- Remove the icon from the right side >.
- Add new icon at the left side with two states, checked and unchecked.
- Permit multi-select of options. 
Check "MultiSelect List view" http://coverwallet.github.io/cw-components/basic/
As usual. …
=> Add multi-select component

examples/basic/app.js, examples/basic/catalog_api_json/industries.js, lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, lib/components/OnlyClickMultiSelect.jsx, lib/stylesheets/components/_oc_list_option.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/n/projects/2105824/stories/152349082
* **Rollbar Errors:** No
* **Related PRs:** No
Add a tooltip in options for multi-select component. Dzmitry provided a link https://projects.invisionapp.com/share/M8E4SN665#/screens/261276881
Added a help-icon for options which has tooltipKey in OnlyClickListOption component.
Check "MultiSelect List view" http://coverwallet.github.io/cw-components/basic/
As usual.
None.
=> Add tooltip for multi-select component

examples/basic/app.js, examples/basic/catalog_api_json/insuranceTypes.js, lib/components/OnlyClickIconOption.jsx, lib/stylesheets/components/_oc_icon_option.scss, package.json
* **Pivotal Story:** https://www.pivotaltracker.com/n/projects/2037291/stories/153097906
Add ability to highlight some insurance products in the insurance type page.
Added property 'recommendable' for the OnlyClickIconOption component, styles and an example
=> OnlyClickIconOptions: add ability to highlight recommendable options

lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, lib/components/OnlyClickSelect.jsx, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/ZUR-799
As a user I want to be able to search for industries if I don't use accents or special characters
Add ability to pass sanitizer function to typeahead's highlight
=> Add ability to pass sanitizer function to typeahead's highlight

package.json
npm doesn't publish the new version because this error: "You cannot publish over the previously published versions: 2.8.2". I guess this happens because the version isn't manually changed in the package.json.
=> Change version in order to npm allows to publish it

package.json, yarn.lock
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-28
The browser was freezing when the pipe character was typed in the input of the OnlyClickSelect in the InsurancePage. In the end, the bug was in the react-hightlight-words library: https://github.com/bvaughn/react-highlight-words/issues/42 
Updating react-hightlight-words lib.
=> Autocomplete input fields failure when informing the pipe character

package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-160
* **Related PRs:** https://github.com/coverwallet/cw-components/pull/120
Change again version number because npm doesn't publish 2.8.5
=> Fix version number because npm doesn't publish 2.8.5

lib/stylesheets/components/_icons_radio_group.scss, package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-160 (this is a fix related with this story, I need to do this in order to finish what the user story says)
Fix icon radio group text when its label has 2 lines instead of one. This can be understood better with images (look at the screenshots). @marlex knows about this and she has helped me to fix it.
Before:
After:
=> Make texts with 2 lines being more adjusted

lib/components/OnlyClickListOption.jsx, lib/stylesheets/components/_oc_list_option.scss
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/ZUR-1819
Due to changes made on refactoring, OnlyClickListOption component is broken now and shows tooltips misaligned.
We have applied a class over the container to make this container to have `display: table`.
=> ZUR-1819 - Fix missaligned tooltip icon on OnlyClickListOption

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/components/__tests__/OnlyClickSelect.test.jsx
* **JIRA Story:** https://coverwallet.atlassian.net/browse/ACQ-522
We need this in order to set a flag when the form is submitted pressing the `Enter` key. The usual behavior of the submit event is triggering the click event of the submit button of the form, that's why we can't use the `onClick` of the submit button. We can’t use the ` OnlyClickSelect `'s `onChange` prop either because this `onChange` is the React’s one, not the native one, so it is not triggered when the `Enter` key is pressed.
Adding a new optional prop `onEnterKeyPress` which is called when the `keypress` event is triggered and the `key` pressed is the `Enter` key.
`yarn test lib/components/__tests__/OnlyClickSelect.test.jsx`
=> Add key event handler to OnlyClickSelect

lib/components/OnlyClickListOptions.jsx, lib/components/__tests__/OnlyClickListOptions.test.jsx, package.json
An error is thrown when no selectedOptions are passed as prop to OnlyClickListOptions component.
Adding fallback to avoid error when there is not selectedOptions prop.
=> OnlyClickListOptions - Fix selectedOptions error when not informed

lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx, lib/stylesheets/components/_icons_radio_group.scss, package.json
Enabling select options without icon.
- Using no-icon modifier.
In addition to that we also did:
- Remove 2 level selectors.
- Add className properties to both components.
- Remove margin/padding top when there is no icon (so that is centred vertically)
Previous:
Actual:
Would have loved to change component name to selectBoxComponent or something similar since it will not need icons anymore, but that would mean a mayor release.
=> Radio group without icon

examples/basic/app.js, lib/components/ButtonsListSelect.jsx, lib/components/ButtonsListSelectOption.jsx, lib/components/ButtonsListSelectOptions.jsx, lib/components/__tests__/ButtonsListSelect.test.jsx, lib/stylesheets/components/_wide_button.scss, package.json
* **JIRA Story:** 
https://coverwallet.atlassian.net/browse/ACQ-542
https://coverwallet.atlassian.net/browse/ACQ-652
- Add 2 differents callbacks for open and close accordion (aka tooltip), so we can do different things when the accordion is open or closed.
- Fix styles of the accordion because the borders of the accordion opened were being duplicated.
`yarn test lib/components/__tests__/ButtonsListSelect.test.jsx`
=> Add open and close tooltip callbacks to ButtonsListSelect

examples/basic/app.js, lib/components/OnlyClickListOption.jsx, lib/components/OnlyClickListOptions.jsx, package.json
Currently, we are hiding the arrows in `OnlyClickListOptions` components by css in SHF. In order to avoid doing that, we are adding a prop that will render conditionally those arrows.
Adding the prop to `OnlyClickListOptions` and passing it down to `OnlyClickListOption`.
Updating minor package version.
=> Adding withArrows prop to OnlyClickListOptions

lib/stylesheets/components/_oc_multi_select_dropdown.scss, package.json
Options in `OnlyClickMultiSelectDropdown` component should maintain UI style even when there is no addition in the option object.
Adding a min-height and giving a class more specificity to avoid styles from other class to affect it.
Previous:
With Change:
=> Fixed ui when options provided have no addition value

examples/basic/app.js, lib/components/OnlyClickSelect.jsx, lib/stylesheets/components/_oc_select.scss, package.json
Added 3 new options for OnlyClickSelect layout:
- smallInput: Make the input smaller.
- grayBorder: Make the border of the input gray.
- noArrows: Make the list has no arrows.
=> Fix: smallInput, grayBorder & noArrows for OnlyClickSelect

lib/components/ButtonsListSelectOption.jsx, package.json
While using the ButtonsListSelect  component I have detected that we never check if methods `onOpenHelp`and `onCloseHelp` exists. I have added an extra check to determine if this methods exists to avoid their execution if they don't exists
Simply by perform a check before execute it.
=> Add extra check to ensure methods onOpenHelp and onCloseHelp exists

lib/stylesheets/components/_oc_icon_options.scss, package.json
* **Jira Story:** https://coverwallet.atlassian.net/browse/AON-283
Tooltip's position is different from design.
Modifying position.
Before:
After:
=> Fixing tooltip's position in icon options

lib/stylesheets/components/_tooltip.scss
Currently we have animation bug on all our component with buttons. It happends because of the 
"~cw-styleguide/bower_components/material-design-lite/src/tooltip/tooltip" that was imported. In that file we have, that overlaps .pulse that we have in cw-components.
=> Delete the import of mdl styles

examples/basic/app.js, examples/basic/app.scss, examples/basic/sample-components/card-component-example.jsx, examples/basic/sample-components/card-component-example.scss, lib/components/CardGroup.jsx, lib/index.js, lib/stylesheets/components/_card.scss, lib/stylesheets/components/_components.scss, package.json
We need to add a component like this
only the card group container. This component should be capable to receive a child component to render it into each card.
We have added a block on cw-components demo page. to see how it works
This is the result
=> Create cards components

lib/stylesheets/components/_input_keyboard.scss, lib/stylesheets/components/_number_input.scss, package-lock.json, package.json
_https://coverwallet.atlassian.net/browse/ACQ-1011_
Last upload of cw-components (v2.25.1) left no padding when removing spinner. Also, a remaining spinner was found for input-keyboard classes. 
Padding has been added and checked for all components (10px, as seen in similar components). Spinner has been removed for input-keyboard, as previously done for input[type+number].
=> Padding and spinners in number inputs

lib/components/NumPadMobile.jsx, package.json
Fix naming in SetNextValue function, because setValue was never passed from the father component.
=> Fix naming in setNextValue func

lib/stylesheets/components/_checkbox_icon.scss, lib/stylesheets/components/_wide_button.scss, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/AONC-1449
Bizpack upfront selection buttons are not being selected when the customer clicks them close to the left end
1. Get to the BI4 upfront selection page
2. Click any of the coverages' buttons close to the left end
The coverage should become selected/deselected
The button does an animation but the coverage does not get selected/deselected
=> AONC1449 - Fix Radio button's inconsistent behavior

examples/basic/sample-components/card-component-example.scss, lib/stylesheets/components/_card.scss, lib/stylesheets/components/_cw_flash_notification.scss, lib/stylesheets/components/_icons_radio_group.scss, lib/stylesheets/components/_oc_icon_options.scss, lib/stylesheets/components/_oc_select.scss, lib/stylesheets/components/_oc_selected_value.scss, package-lock.json, package.json
We have a lot of warnings due to use of outdated styles
This is happening because we use deprecated bourbon flexbox mixins
https://www.bourbon.io/docs/4/#flexbox
Flexbox is fully supported by all browsers, so we dont have to use external tools.
Change bourbone mixins to regular flexbox styles
=> CHORE / Remove deprecated flex mixins

lib/components/CwFlashNotification.jsx, package-lock.json, package.json
* **JIRA Story:** https://coverwallet.atlassian.net/browse/DBS-3284
We need to add a `data-test` to the parent container of the flash notification. This `data-test` is used in cypress tests.
=> DBS 3284 - Add data-test to CWFlashNotification

lib/components/CurrencyInput.jsx, lib/components/IconRadioGroup.jsx, lib/components/IconRadioInput.jsx
Add ref to props in order to be able to set them instead of a fixed String
Related PR: https://github.com/coverwallet/cw-node-wallet-admin/pull/110
=> add ref for components in wallet-admin

lib/components/IconRadioGroup.jsx, package-lock.json, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/IN-2874
clicking on button triggers onChange 2 times.
before:
after:
=> Fix onChange triggered twice on button click

lib/components/InputKeyboard.jsx, package-lock.json, package.json
* **Pivotal Story:** https://coverwallet.atlassian.net/browse/LANN-2904
* **Related PRs:** https://github.com/coverwallet/cw-node-wallet-frontend/pull/69
Add `ref` prop to `InputKeyboard` component so it can be used with `react-hook-form`
=> LANN-2904 add ref prop to inputKeyboard
